# --- Database Settings ---
database_settings:
  database_file: "massgov_updates.db"

# --- Agent Settings ---
agent_settings:
  # Base URL format for the daily CSV files on GitHub.
  # The {date} placeholder will be replaced with the correct YYYY-MM-DD string.
  github_csv_url_format: "https://raw.githubusercontent.com/JonGerhardson/massgovupdates/main/daily_updates/{date}.csv"
  
  # How many days back to consider a page "new".
  # 2 means yesterday and the day before are considered new.
  recency_threshold_days: 2
  
  # --- Rate Limiting to avoid being blocked ---
  # The agent will wait a random amount of time between these two values (in seconds)
  # before making each web request to mass.gov.
  rate_limit_min: 1.0
  rate_limit_max: 3.0

# --- LLM Provider Settings ---
llm_settings:
  # Choose your provider: "gemini", "openrouter", or "lmstudio"
  provider: "gemini"

  # Maximum number of characters to send to the LLM from any document.
  character_limit: 8000

  # --- API Keys ---
  # For Gemini, you can also set the GEMINI_API_KEY environment variable.
  api_keys:
    gemini: "YOUR_GEMINI_API_KEY"
    openrouter: "YOUR_OPENROUTER_API_KEY"

  # --- Endpoints for OpenAI-compatible APIs ---
  endpoints:
    openrouter: "https://openrouter.ai/api/v1/chat/completions"
    lmstudio: "http://localhost:1234/v1/chat/completions"
    
  # --- Model Selection ---
  # Specify the exact model identifier for each service.
  models:
    gemini: 'gemini-2.0-flash'
    openrouter: 'google/gemini-2.5-flash'
    lmstudio: 'qwen3-4b-128k'

